# config for wiserdocs

reportName: wiserDocs
reportDescription: Undergraduate files with an existing application

# path to where to look for directories within
unzipPath: Y:\DI_###ENV_U3###_INBOUND\1_unzip
errorPath: Y:\DI_###ENV_U3###_INBOUND\error
# can use globs
csvFileName: di_databank_wiserapp-files.csv

addToQueue: Import Complete
alertEmails:
  - user1@umass.edu

staticValues:
  - name: Drawer
    type: IDX
    value: UMUA
  - name: Document App Plan
    type: CP
    value: UMBUA_Import.js - Wiser


csvValues:
  - name: filename
    type: path
  - name: drawer
    type: none
  - name: folder
    type: index
  - name: tab
    type: index
  - name: f3
    type: index
  - name: f4
    type: index
  - name: f5
    type: index
  - name: docTypeName
    type: index
  - name: SA Application Nbr
    type: CP
  - name: Document App Plan
    type: none
  - name: CEEB
    type: CP
  - name: SA Org ID
    type: CP
  - name: Recommender Name
    type: CP
  - name: Needs Data Entry
    type: CP
  - name: Checklist Update
    type: CP
  - name: Source
    type: CP
  - name: Career
    type: CP
  - name: App Center
    type: CP
  - name: tmp_preapp-Emplid
    type: CP
  - name: tmp_preapp-fname
    type: CP
  - name: tmp_preapp-lname
    type: CP
  - name: tmp_preapp-mname
    type: CP
